spring:
  profiles:
    active: dev
server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
application:
  security:
    jwt:
      secret-key: green_stone_gsfwrebirth
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days